### ISSUE TITLE
Deprecated apiVersion for Ingress

### ISSUE THREAD

**Issue by Lunik** [jfrog/charts#1315]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 3.4.2 for Kube v1.18.10

**Which chart**: artifactory, xray

**What happened**:
The Ingress resource is not created with the right `apiVersion`.
Currently : `extensions/v1beta1`

**What you expected to happen**:
The Ingress resource should have `apiVersion` equal to `networking.k8s.io/v1beta1`

**How to reproduce it** (as minimally and precisely as possible):
Deploy the chart.

**Anything else we need to know**:

The `if` statement at this location (and other) may be guilty: https://github.com/jfrog/charts/blob/master/stable/artifactory/templates/ingress.yaml#L6
Should not use deprecated `.Capabilities.KubeVersion.GitVersion` (since Helm 3).

`Capabilities.APIVersions.Has` should be used for api version Check ([as specified in the Helm documentation](https://helm.sh/docs/chart_template_guide/builtin_objects/#helm))

**Comment by mickeder** [comment]
I don't know why this was closed, since I'm facing the same issue with Helm 3.5.2 and Kubernetes v1.19.6-eks-49a6c0.
The problem is already described, but I can confirm that Helm 3 does not support Capabilities.KubeVersion.GitVersion, so the ingress `apiVersion` installed is `extensions/v1beta1` and it should be `networking.k8s.io/v1beta1`
