### ISSUE TITLE
Request for seccomp profiles

### ISSUE THREAD

**Issue by ralpht42** [jfrog/charts#1730]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Which chart**: Artifactory and x-ray

**Which product license** (Enterprise/Pro/oss): Enterprise

We need a support for seccomp profiles (e.g. RuntimeDefault). The templates only offer specific securityContext entries, but there's no option for setting seccomp profiles for a pod/container.

**Comment by kammathavaran** [comment]
Can you provide a example for the profile that needs to be added ?

**Comment by Logeshwarsn** [comment]
@RalphTordai Gentle reminder !! Please provide us some example for the profile

**Comment by RalphTordai** [comment]
I think that to start with the profile from "Runtime/Default", which is by default in Kubernetes, would provide the basic security benefits. However, a detailed solution would be a profile tailored to Artifactory/X-Ray that disallows all syscalls that are not needed. However, this is unlikely to be possible in the foreseeable future due to the high complexity involved.

https://kubernetes.io/docs/tutorials/security/seccomp/#create-pod-that-uses-the-container-runtime-default-seccomp-profile

**Comment by srinivasgowda097** [comment]
@ralpht42  Thank you, we would add internal tracking improvement, further if your interested in contributing please feel free to raise pull request for the same

**Comment by gitta-jfrog** [comment]
Added https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L178
