### ISSUE TITLE
Registration with router on URL http://localhost:8046 failed with error: UNIMPLEMENTED: HTTP status 404 page not found

### ISSUE THREAD

**Issue by AustinZheng-chaos** [jfrog/charts#1935]
helm Version:"v3.15.4"
Kubernetes ：v1.28.2
Which chart ： ![Image](https://github.com/user-attachments/assets/3adacae8-ac53-4c43-a2bb-af6d87dbdfdb)
What happened:
![Image](https://github.com/user-attachments/assets/378f3fcc-6719-48cd-bfc8-cbd3b3dc53c3)
key point：Registration with router on URL http://localhost:8046 failed with error: UNIMPLEMEupNTED: HTTP status 404 page not found
I have saw the “issues/857“，but the advice of  increase the resources of Mem or Cpu didn't works,my environment is totally a new cloud server cluster with 4 nodes，every node has 16C and 64G，and there is not other service on it，so basically my problem doesn't match “issues/857“.
Here is my private values.yaml:
![Image](https://github.com/user-attachments/assets/453e96d5-1da4-47eb-ba96-da4cef0c6180)
my helm cmd is :helm install artifactory jfrog/artifactory --version 107.41.6 -f values.yaml -n artifactory

God,please help me with this issue,i have been trying to solve it for 1 week but still useless,i would be sincerely appreciated of somebody could give me an assistance,Ty!!!

**Comment by ashraf-kherbawy** [comment]
Hello Austin

Both the Access and Artifactory micro-services are complaining that Router is not found. Can you check the router-service.log to see if it's printing anything? If not, then it seems Router is down, and we would need to investigate the reason for it. This seems more of an application issue rather than a Helm Chart issue.
