### ISSUE TITLE
Health check path

### ISSUE THREAD

**Issue by brunomanzo** [jfrog/charts#471]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:

**Which chart**:
artifactory

**What happened**:

**What you expected to happen**:
I want to use the correct path for HC checking: https://jfrog.com/knowledge-base/what-is-the-best-practice-to-configure-a-health-check-for-artifactory-in-amazon-elb/
But i don't see how to configure this on the current chart.

Also I saw that the pod uses this path to check HC:
    Liveness:       http-get http://:8040/artifactory/webapp/%23/login delay=90s timeout=10s period=10s #success=1 #failure=10

But 8040 isn't exposed.

I am using '/' to HC, since it returns 200

```
% curl -v 172.30.8.166:8081/
*   Trying 172.30.8.166...
* TCP_NODELAY set
* Connected to 172.30.8.166 (172.30.8.166) port 8081 (#0)
> GET / HTTP/1.1
> Host: 172.30.8.166:8081
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< ETag: W/"878-1568124623000"
< Last-Modified: Tue, 10 Sep 2019 14:10:23 GMT
< Content-Type: text/html
< Content-Length: 878
< Date: Wed, 18 Sep 2019 13:09:30 GMT
< 
<!--
  ~ Artifactory is a binaries repository manager.
  ~ Copyright (C) 2018 JFrog Ltd.
  ~
  ~ Artifactory is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Artifactory is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with Artifactory.  If not, see <http://www.gnu.org/licenses/>.
  -->
<html>
<head>
	<meta http-equiv="refresh" content="0;URL=/artifactory">
</head>
<body>
</body>
</html>
```

But I want to make it right using the appropriate endpoint.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by eldada** [comment]
Hi @brunomanzo. There are several options for this.
The [article] (https://jfrog.com/knowledge-base/what-is-the-best-practice-to-configure-a-health-check-for-artifactory-in-amazon-elb/) you mentioned is correct. Using the `/artifactory/api/system/ping` endpoint is the best option, but does require you set `artifactory.ping.allowUnauthenticated=true` as noted. We don't use it because we want to leave it up to the user to decide if to allow unauthenticated access to `/artifactory/api/system/ping`.

The endpoint `/artifactory/webapp/#/login` we use today is a simpler way as the login screen is also a good indicator system is up. We use port 8040, which is Access' port, to avoid the case where a load on Artifactory will block all connections on port 8081 and fail the livenessProbe. It's used internally so not exposed on the pod. 

The `/` endpoint will work but might hide some errors that are preventing the system to fully come up.

**Comment by brunomanzo** [comment]
@eldada Hello there!

But how I can modify that variable? I don't see how to change this on this chart, I should override the file by mouting the directory?

**Comment by eldada** [comment]
The probe path? `artifactory.readinessProbe.path` and `artifactory.livenessProbe.path`.
What file do you mean?

**Comment by eldada** [comment]
@brunomanzo - do you want to continue this?

**Comment by brunomanzo** [comment]
Hello @eldada, sry for not responding, we can close this, thanks!!!
