### ISSUE TITLE
Postgres Password in Configmap/Secret Reseting

### ISSUE THREAD

**Issue by evannorstrand** [jfrog/charts#545]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
K8s - 1.15.1
Helm - Whatever rancher uses

**Which chart**:
Artifactory

**What happened**:
Whenever Artifactory restarts, the configmap containing the password for the database restarts.

**What you expected to happen**:
The password to stay static

**How to reproduce it** (as minimally and precisely as possible):
Redeploy Artifactory

**Anything else we need to know**:

**Comment by nmccready** [comment]
We are seeing this as well.

**Comment by danielezer** [comment]
Hey @evannorstrand @nmccready, this is actually a known issue with helm. Because the postgres chart uses `randAlphaNum` to generate a random password - https://github.com/helm/charts/blob/master/stable/postgresql/templates/_helpers.tpl#L89. When using `randAlphaPassword`, any time you run `helm upgrade`, a new password is randomly generated. This means that the secret may not always reflect the real postgres password. There's an open issue in helm about that - https://github.com/helm/charts/issues/5167, hopefully there will be a solution some day for not re-generating the random password on every upgrade. In the mean time, the best practice when using any of the JFrog charts, is to provide a DB password in your `values.yaml` file instead of letting helm generate a random one for you.

**Comment by evannorstrand** [comment]
@danielezer - We have the password set in the helm chart and this issue is persisting.

**Comment by danielezer** [comment]
@evannorstrand can you share your values file?
