### ISSUE TITLE
Latest published Artifactory chart doesn't match master code

### ISSUE THREAD

**Issue by admoriarty** [jfrog/charts#654]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2 (maybe relevant to how "latest" is pulled?)

**Which chart**:
Artifactory

**What happened**:

The latest published package which is being pulled by default appears to be a 9.x chart (https://charts.jfrog.io/artifactory-9.0.14.tgz), but the code in master of https://github.com/jfrog/charts/tree/master/stable/artifactory is clearly still the 8.x code (judging by the upgrade notes and the annoying issue we had locally trying to use values that no longer work as they've been renamed :) )

**What you expected to happen**:
The latest code matches the latest release

**How to reproduce it** (as minimally and precisely as possible):
Follow the basic README under https://github.com/jfrog/charts/tree/master/stable/artifactory and it will pull the latest 9.x

**Anything else we need to know**:

**Comment by eldada** [comment]
Hi @admoriarty. We are going to publish the sources for the new charts in the coming days. We were developing them internally and are in the process of preparing them for GitHub.
Sorry for the inconvenience.

**Comment by admoriarty** [comment]
Thanks for that explanation @eldada but wouldn't it be prudent to delete that 9.x artifact to avoid this confusion, until the code matches the helm repo?

**Comment by eldada** [comment]
There were some other considerations behind this 😄. Anyway, hope to publish soon.

**Comment by Hokwang** [comment]
OMG I realize this now!

**Comment by sgryczan** [comment]
Ha! This just bit me as well. I was wondering why my manifests weren't rendering correctly, not realizing the source had changed. Glad I'm not crazy 😄

**Comment by eldada** [comment]
Sorry all. I hope to have good news in the coming days. We are working hard to get the sources cleaned up and ready to be published.
You can still get them by fetching the chart and extracting it:
```
helm repo add jfrog https://charts.jfrog.io
helm fetch jfrog/artifactory
tar xzf artifactory-*.tgz
```

NOTE: The chart's final sources are still WIP.

**Comment by ahs-dev** [comment]
Hi there, are you already accepting questions or looking for feedback for these WIP charts?

We evaluated some Artifactory V6 to V7 migration scenarios using the new chart and ran into problems.

We don't use dynamic provisioning and set the parameters to use preconfigured claims via
`artifactory.persistence.existingClaim: "existing-claim-name"`
which works nice up to chart version 8.0.15, but causes problems while updating to 9.X, such as

`Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

because the 'volumeClaimTemplates' segment of the artifactory-statefulset.yaml is now always present in the rendered template and not removed when 'existingClaim' is set

When we force to recreate all resources during the upgrade, kubernetes will not complain about the changed spec, but will complain about the 'volumeClaimTemplates' segment being invalid.

Are you about to remove support for preconfigured pvcs or was this an oversight.

**Comment by JfrogPrasanna** [comment]
Hey guys, the charts are now aligned with latest 7.x versions. Please let us know if all is ok. Closing  this issue,  which was more related to "Latest published Artifactory chart doesn't match master code"  which  is now aligned. Please have a look at upgrade notes as well,  to get to this version.
