### ISSUE TITLE
Support encrypted artifactory.config.import.xml file

### ISSUE THREAD

**Issue by sylus** [jfrog/charts#86]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Version of Helm and Kubernetes**:

Kubernetes: v1.10.6
Helm: v2.9.1

**Which chart**: Artifactory

**What happened**:

I was hoping we could extend the chart to support encrypted configuration. I discovered this by realizing there was no configuration for the `artifactory.key` under the /var/opt/jfrog/artifctory/etc/security folder. So was why my custom configmap always failed. I have been resorting to:

```sh
kubectl cp artifactory.key monitoring/artifactory-artifactory-0:/var/opt/jfrog/artifactory/etc/security/
```

**What you expected to happen**: Configuration to be added to support encrypted configmaps.

**How to reproduce it** (as minimally and precisely as possible): N/A

**Anything else we need to know**: N/A

**Comment by sylus** [comment]
@jainishshah17

**Comment by danielezer** [comment]
@sylus do you mean password encryption? https://www.jfrog.com/confluence/display/RTF/Artifactory+Key+Encryption

Which version of the helm chart are you using?

**Comment by gangefors** [comment]
I know this is an old and closed feature request. But I am looking for a way to use kubernetes secrets to seed the artifactory.key so that I am able to deploy a new environment, using a DB and filesystem backup, without the need to resorting to a complex solution trying to get the encryption key into the pod filesystem.

Why not support the artifactory.key in the same manner that you support the master/join keys?

Or am I missing something?
